development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ref_area_dev
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ref_area_prod
  pool: 5
  username: root
  password: 
  host: localhost
